server.port=${PORT:8080}

# =========================
# PostgreSQL
# Local por defecto / Render con variables de entorno
# =========================
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/whatsapp_clon}
spring.datasource.username=${DATABASE_USERNAME:caballerito}
spring.datasource.password=${DATABASE_PASSWORD:ola23}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# JWT
# =========================
bezkoder.app.jwtSecret=${JWT_SECRET:whatsappRealSecretKeyTemporal123456789}
bezkoder.app.jwtExpirationMs=86400000